[package]
name = "unlade-dependencies-parser"
description = "Counts the crates depending on each crate in a crates.io dump"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["crates-io", "dependencies", "database", "analysis"]
categories = ["development-tools"]

[lib]
path = "lib.rs"

[dependencies]
thiserror.workspace = true
unlade-core = { version = "0.1.0", path = "../unlade-core" }
unlade-parser.workspace = true

[dev-dependencies]
unlade-crates-parser = { version = "0.1.0", path = "../unlade-crates-parser" }
